config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :sessions

  resources :activities

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: "delete"

  root 'welcome#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  enum member: [ :member, :visitor, :applying, :former ]
  validates :name, presence: true, length: { maximum: 20 }
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :classroom, presence: { if: lambda { self.applying? || self.member? } }

  before_save { self.username = username.downcase }
  before_create :create_remember_token

  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.hash(User.new_remember_token)
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:sessions][:username])
    if user && user.authenticate(params[:sessions][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = "用户名或密码错误"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if params[:user][:member] == "0"
      @user.member = "applying"
      @user.classroom = params[:user][:classroom]
    end
    if @user.save
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :name, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.hash(User.new_remember_token))
    current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(remember_token: User.hash(cookies[:remember_token]))
  end

  def signed_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wxyzipa</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="https://dn-staticfile.qbox.me/jquery/2.1.1/jquery.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-controller="<%= controller_name %>">
  <div class="body">
    <header>
      <a href="/" id="logo"></a>
      <nav>
        <ul id="top_nav">
          <% if signed_in? %>
          <li id="left" class="p">欢迎，<%= current_user.name %></li>
          <li class="p"><%= link_to "登出", signout_path, method: "delete" %></li>
          <% else %>
          <li id="left" class="p"><%= link_to "注册", signup_path %></li>
          <li class="p"><%= link_to "登录", signin_path %></li>
          <% end %>
        </ul>
      </nav>

      <nav>
        <ul id="menu">
          <li><%= link_to "INTRO", root_path %></li>
          <li><a id="activities">ACTIVITIES</a></li>
          <li><a id="works">WORKS</a></li>
          <li><%= link_to "MEMBERS", current_user || signin_path, id: "members" %></li>
          <li><a id="contacts">CONTACTS</a></li>
        </ul>
      </nav>
    </header>

    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "flash flash-#{key}" %>
      <% end %>
      <%= yield %>
    </div>

    <footer>
      <small>Copyright 2014 Information & Photography Association. All Rights Reserved.</small>
    </footer>

  </div>
</body>
</html>

app/views/users/new.html.erb
<div id="signup">
  <h1>用户注册</h1>
  <% if @user.errors.any? %>
    <div class="form-error">
      <p>请检查你的提交表单</p>
      <ul>
        <% @user.errors.full_messages.each do |e| %>
          <li><%= e %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for @user do |f| %>
    <%= f.label :username, "用户名：", class: "t-label" %>
    <%= f.text_field :username %>

    <%= f.label :name, "姓名：", class: "t-label" %>
    <%= f.text_field :name %>

    <%= f.label :password, "密码：", class: "t-label" %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "密码确认：", class: "t-label" %>
    <%= f.password_field :password_confirmation %>

    <%= f.label :member, "是否为社员：", class: "t-label" %>
    <%= f.radio_button :member, 0 %>
    <%= f.label :member, "是", value: 0 %>
    <%= f.radio_button :member, 1, checked: true %>
    <%= f.label :member, "否", value: 1 %>

    <%= f.label :classroom, "班级：", class: "t-label classroom", id: "classroom-label" %>
    <%= f.text_field :classroom, class: "classroom" %>

    <%= f.submit "提交" %>

  <% end %>
</div>

app/views/users/show.html.erb
<aside id="side">
  
</aside>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="flexslider">
    <ul class="slides">
      <li><img src="https://dn-ipa-public.qbox.me/publicphoto.jpg" /></li>
      <li><img src="https://dn-ipa-public.qbox.me/publicpost.jpg" /></li>
      <li><img src="https://dn-ipa-public.qbox.me/publichard.jpg" /></li>
      <li><img src="https://dn-ipa-public.qbox.me/publicpub.jpg" /></li>
    </ul>
  </div>
</div>
<div class="about">
  <div id="about">
    <h1>
    <div class="line left"></div>
      About us
    <div class="line right"></div
    </h1>
  </div>
  <p>
    IPA（Information Photography Association）是由幻飘摄影协会和ITU信息技术协会合并而成的社团。作为无锡一中最早创立的社团之一，IPA从未停止过前进的脚步。从最初的幻飘工作室，经过6年风雨，如今我们举办大型摄影展,制作《雕刻时光》光碟,编辑报纸，举办计算机比赛，维护学校网站。我们参加了各种全国科技创新大赛，并屡创佳绩。IPA不负众望，成长为无锡一中最成熟最强大的社团之一，收获了“无锡市十佳社团”的荣誉。这里面的每一步脚印都浸透着我们的汗水。因此，我们可以自豪的说，我们是IPA协会，我们是IPAers。我们爱摄影，爱后期，也爱装机写程序软件。
  </p>
</div>